<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableArchitectureAnalyzer>true</EnableArchitectureAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PSXRecomp.Core/PSXRecomp.Core.csproj" />
  </ItemGroup>
</Project>
